import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/session_provider.dart';
import '../providers/auth_provider.dart';
import '../models/session.dart';

class CreateSessionScreen extends StatefulWidget {
  const CreateSessionScreen({super.key});

  @override
  _CreateSessionScreenState createState() => _CreateSessionScreenState();
}

class _CreateSessionScreenState extends State<CreateSessionScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _locationController = TextEditingController();
  String _type = 'Lecture';
  String _dayOfWeek = 'Monday';
  TimeOfDay _startTime = TimeOfDay(hour: 9, minute: 0);
  int _duration = 1;

  final List<String> _days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

  void _submit() async {
    if (_formKey.currentState!.validate()) {
      final userId = Provider.of<AuthProvider>(context, listen: false).user!.id;
      final session = Session(
        id: '', // Generated by backend
        title: _titleController.text,
        type: _type,
        dayOfWeek: _dayOfWeek,
        startTime: _startTime.format(context),
        duration: _duration,
        location: _locationController.text,
        attendance: [],
      );

      try {
        await Provider.of<SessionProvider>(context, listen: false).createSession(userId, session);
        if (!mounted) return;
        Navigator.of(context).pop();
      } catch (e) {
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Add Class')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              TextFormField(
                controller: _titleController,
                decoration: InputDecoration(labelText: 'Subject / Title'),
                validator: (val) => val!.isEmpty ? 'Please enter a title' : null,
              ),
              DropdownButtonFormField<String>(
                initialValue: _type,
                items: ['Lecture', 'Lab'].map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(),
                onChanged: (val) {
                  setState(() {
                    _type = val!;
                    _duration = _type == 'Lecture' ? 1 : 2;
                  });
                },
                decoration: InputDecoration(labelText: 'Type'),
              ),
              DropdownButtonFormField<String>(
                initialValue: _dayOfWeek,
                items: _days.map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(),
                onChanged: (val) => setState(() => _dayOfWeek = val!),
                decoration: InputDecoration(labelText: 'Day'),
              ),
              ListTile(
                title: Text('Start Time: ${_startTime.format(context)}'),
                trailing: Icon(Icons.access_time),
                onTap: () async {
                  final time = await showTimePicker(context: context, initialTime: _startTime);
                  if (time != null) setState(() => _startTime = time);
                },
              ),
              TextFormField(
                controller: _locationController,
                decoration: InputDecoration(labelText: 'Location / Room'),
              ),
              SizedBox(height: 20),
              ElevatedButton(onPressed: _submit, child: Text('Save')),
            ],
          ),
        ),
      ),
    );
  }
}
